### PR TITLE
No results page

### PR DESCRIPTION
**Pull request by asadovka**
https://github.com/cybercongress/cyb/tree/no-results-page/design/.exportedArtboards/No%20results%20page

# ver. 1

image

# ver. 2

image

### CODE REVIEW

**Comment by asadovka** [comment]
grammar mistake in first version(

-> couldn't

**Comment by litvintech** [comment]
@asadovka version 2 are good for now, 
think that it will be good to add "Vitalik 42 logo" to this page

**Review by cyborgshead — COMMENTED** [review]
@asadovka version 2 are good for now,
think that it will be good to add "Vitalik 42 logo" to this page
@asadovka @Olga584 What do you think about it?

**Comment by asadovka** [comment]
the latest version

**Pull request closed without merging**
